name: CICD-Test-Context

on: [push]

env:
  Greeting: Hello

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test Environment Variables
        run: |
          echo "${{ env.Greeting }} from $(whoami)"
      - name: Test Secret Variables 1
        run: |
          echo "super_secret: ${{ secrets.SuperSecret }}"
      - name: Test Secret Variables 2
        env:
          super_secret: ${{ secrets.SuperSecret }}
        run: |
          echo "super_secret: ${{ env.super_secret }}"
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for reporting...'
            })
