name: Testing Secrets

on:
  pull_request:
    branches: 
      - master
      - myfeature

jobs:
  print_secrets:
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: write

    steps:
      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Hello world ! :wave:
